### ISSUE TITLE
Every second frame is black

### ISSUE THREAD

**Issue by gardiiinc** [Mar2ck/DAIN-Vulkan-GUI#3]
Thanks for sharing your code.
I've got a problem, it doesn't work :)
Linux Mint 20 RTX 2060 S Conda/pip
dain-ncnn-vulkan-artifact-ubuntu-20.04.zip downloaded and unzip in
DAIN-Vulkan-GUI/src/dependencies
Structure:
DAIN-Vulkan-GUI/src/dependencies/dain-ncnn-vulkan/dain-ncnn-vulkan-ubuntu
with best/ in DAIN-Vulkan-GUI/src/dependencies/dain-ncnn-vulkan
It does run, but every second frame is black and the resulting video is flickering.
./DAINVulkanCLI.py -i "/.../DAIN-Vulkan-GUI/src/in/v01.mp4" -O "/.../DAIN-Vulkan-GUI/src/out" 

Got some error messages:

`Platform: Linux
Interpolator Options: {}
Input file: /.../DAIN-Vulkan-GUI/src/in/v01.mp4
FFprobe: Scanning video metadata for framerate...
{'fpsReal': '30000/1001', 'fpsAverage': '30000/1001'}
Working Directory: /.../DAIN-Vulkan-GUI/src/out/v01
Step 1: Extracting frames to original_frames
Original frame count: 161
Interpolated frame count 322
Step 2: Processing frames to interpolated_frames using dain-ncnn
Interpolating to: 2x
/.../DAIN-Vulkan-GUI/src/dependencies/dain-ncnn-vulkan/dain-ncnn-vulkan-ubuntu -i /.../DAIN-Vulkan-GUI/src/out/v01/original_frames -o /.../DAIN-Vulkan-GUI/src/out/v01/interpolated_frames -n 322 -t 256 -g auto -j 1:1:1 -v
[0 GeForce RTX 2060 SUPER]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 GeForce RTX 2060 SUPER]  bugsbn1=0  buglbia=0  bugcopc=0  bugihfa=0
[0 GeForce RTX 2060 SUPER]  fp16p=1  fp16s=1  fp16a=1  int8s=1  int8a=1
fopen depthnet.param failed
fopen depthnet.bin failed
fopen flownet.param failed
fopen flownet.bin failed
fopen ctxnet.param failed
fopen ctxnet.bin failed
fopen interpolation.param failed
fopen interpolation.bin failed
find_blob_index_by_name input failed
find_blob_index_by_name depth failed
find_blob_index_by_name input failed
find_blob_index_by_name depth failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name flow failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name flow failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name depth0 failed
find_blob_index_by_name depth1 failed
find_blob_index_by_name flow0 failed
find_blob_index_by_name flow1 failed
find_blob_index_by_name flow0_w failed
find_blob_index_by_name flow1_w failed
find_blob_index_by_name ctx0 failed
find_blob_index_by_name ctx1 failed
find_blob_index_by_name output_rectified failed
find_blob_index_by_name input failed
find_blob_index_by_name depth failed
find_blob_index_by_name input failed
find_blob_index_by_name depth failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name flow failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name flow failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name depth0 failed
find_blob_index_by_name depth1 failed
find_blob_index_by_name flow0 failed
find_blob_index_by_name flow1 failed
find_blob_index_by_name flow0_w failed
find_blob_index_by_name flow1_w failed
find_blob_index_by_name ctx0 failed
find_blob_index_by_name ctx1 failed
find_blob_index_by_name output_rectified failed
find_blob_index_by_name input failed
find_blob_index_by_name depth failed
find_blob_index_by_name input failed
find_blob_index_by_name depth failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name flow failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name flow failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name depth0 failed
find_blob_index_by_name depth1 failed
find_blob_index_by_name flow0 failed
find_blob_index_by_name flow1 failed
find_blob_index_by_name flow0_w failed
find_blob_index_by_name flow1_w failed
find_blob_index_by_name ctx0 failed
find_blob_index_by_name ctx1 failed
find_blob_index_by_name output_rectified failed
find_blob_index_by_name input failed
find_blob_index_by_name depth failed
find_blob_index_by_name input failed
find_blob_index_by_name depth failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name flow failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name flow failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name depth0 failed
find_blob_index_by_name depth1 failed
find_blob_index_by_name flow0 failed
find_blob_index_by_name flow1 failed
find_blob_index_by_name flow0_w failed
find_blob_index_by_name flow1_w failed
find_blob_index_by_name ctx0 failed
find_blob_index_by_name ctx1 failed
find_blob_index_by_name output_rectified failed
find_blob_index_by_name input failed
find_blob_index_by_name depth failed
find_blob_index_by_name input failed
find_blob_index_by_name depth failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name flow failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name flow failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name depth0 failed
find_blob_index_by_name depth1 failed
find_blob_index_by_name flow0 failed
find_blob_index_by_name flow1 failed
find_blob_index_by_name flow0_w failed
find_blob_index_by_name flow1_w failed
find_blob_index_by_name ctx0 failed
find_blob_index_by_name ctx1 failed
find_blob_index_by_name output_rectified failed
find_blob_index_by_name input failed
find_blob_index_by_name depth failed
find_blob_index_by_name input failed
find_blob_index_by_name depth failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name flow failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name flow failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name depth0 failed
find_blob_index_by_name depth1 failed
find_blob_index_by_name flow0 failed
find_blob_index_by_name flow1 failed
find_blob_index_by_name flow0_w failed
find_blob_index_by_name flow1_w failed
find_blob_index_by_name ctx0 failed
find_blob_index_by_name ctx1 failed
find_blob_index_by_name output_rectified failed
find_blob_index_by_name input failed
find_blob_index_by_name depth failed
find_blob_index_by_name input failed
find_blob_index_by_name depth failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name flow failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name flow failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name depth0 failed
find_blob_index_by_name depth1 failed
find_blob_index_by_name flow0 failed
find_blob_index_by_name flow1 failed
find_blob_index_by_name flow0_w failed
find_blob_index_by_name flow1_w failed
find_blob_index_by_name ctx0 failed
find_blob_index_by_name ctx1 failed
find_blob_index_by_name output_rectified failed
find_blob_index_by_name input failed
find_blob_index_by_name depth failed
find_blob_index_by_name input failed
find_blob_index_by_name depth failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name flow failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name flow failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name depth0 failed
find_blob_index_by_name depth1 failed
find_blob_index_by_name flow0 failed
find_blob_index_by_name flow1 failed
find_blob_index_by_name flow0_w failed
find_blob_index_by_name flow1_w failed
find_blob_index_by_name ctx0 failed
find_blob_index_by_name ctx1 failed
find_blob_index_by_name output_rectified failed
find_blob_index_by_name input failed
find_blob_index_by_name depth failed
find_blob_index_by_name input failed
find_blob_index_by_name depth failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name flow failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name flow failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name depth0 failed
find_blob_index_by_name depth1 failed
find_blob_index_by_name flow0 failed
find_blob_index_by_name flow1 failed
find_blob_index_by_name flow0_w failed
find_blob_index_by_name flow1_w failed
find_blob_index_by_name ctx0 failed
find_blob_index_by_name ctx1 failed
find_blob_index_by_name output_rectified failed
find_blob_index_by_name input failed
find_blob_index_by_name depth failed
find_blob_index_by_name input failed
find_blob_index_by_name depth failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name flow failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name flow failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name depth0 failed
find_blob_index_by_name depth1 failed
find_blob_index_by_name flow0 failed
find_blob_index_by_name flow1 failed
find_blob_index_by_name flow0_w failed
find_blob_index_by_name flow1_w failed
find_blob_index_by_name ctx0 failed
find_blob_index_by_name ctx1 failed
find_blob_index_by_name output_rectified failed
find_blob_index_by_name input failed
find_blob_index_by_name depth failed
find_blob_index_by_name input failed
find_blob_index_by_name depth failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name flow failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name flow failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input failed
find_blob_index_by_name ctx failed
find_blob_index_by_name input0 failed
find_blob_index_by_name input1 failed
find_blob_index_by_name depth0 failed
find_blob_index_by_name depth1 failed
find_blob_index_by_name flow0 failed
find_blob_index_by_name flow1 failed
find_blob_index_by_name flow0_w failed
find_blob_index_by_name flow1_w failed
find_blob_index_by_name ctx0 failed
find_blob_index_by_name ctx1 failed
find_blob_index_by_name output_rectified failed
`
Can you help? Thanks.

**Comment by Mar2ck** [comment]
Are the contents of "best" in the same folder as "dain-ncnn-vulkan-ubuntu"? If you download the 0.0.2 release you can just copy the dependencies folder from there into src and that should have everything organised correctly

**Comment by gardiiinc** [comment]
Looks like i was too much in conda/pip install dep puzzle mode, after to much search for another dain solution. :)
I didn't see that you have a release with all necessary, just had to change some permissions. Perfect.
Looking forward for this feature:
Dynamic 1x mode (framerate stays the same but duplicate frames are replaced with interpolations)

while  trying dain on 80s animation.
Thanks

**Comment by Mar2ck** [comment]
Glad it works
