### ISSUE TITLE
Unable to create an info.json

### ISSUE THREAD

**Issue by OJ101003** [Mar2ck/DAIN-Vulkan-GUI#4]
When you try running it, the program cannot create a info.json file in the location of the original video.

![Screenshot 2020-11-16 085523](https://user-images.githubusercontent.com/73129639/99283176-7d6b9d80-27e9-11eb-949a-9d6c81d2729d.png)

**Comment by Mar2ck** [comment]
This has already been fixed and the next release I'll publish will contain the fix so wait for that or use the git version manually

**Comment by OJ101003** [comment]
Ok sounds great! tysm
