### ISSUE TITLE
Audio is not kept, is there a way to implement it?

### ISSUE THREAD

**Issue by Tsubajashi** [Mar2ck/DAIN-Vulkan-GUI#7]
I'm back!
I wanted to ask if its possible to implement to keep the audio from a video file i want to interpolate?
That would remove the need of muxing software for me, and would be a great addition.

**Comment by Mar2ck** [comment]
Yep, it's on my todo list.

**Comment by Tsubajashi** [comment]
Perfect, thanks for the quick response!
I would suggest to use the project function of GitHub, so we all can see your to-do list, and the corresponding status of each refinement or bug fix :)

**Comment by Tsubajashi** [comment]
Just saw that it got implemented, perfect! Thanks. :)
