### ISSUE TITLE
RIFE NCNN dropped tiles, can you implement that its not needed anymore?

### ISSUE THREAD

**Issue by Tsubajashi** [Mar2ck/DAIN-Vulkan-GUI#9]
see title :)

**Comment by Mar2ck** [comment]
Yeah ill update rife-ncnn and cain-ncnn soon now that both are tile-less

**Comment by Tsubajashi** [comment]
Hi!
hope i dont stress you, but i wanted to know how the status on that update is? :D i actually prefer using such a CLI method, and i would really love the performance boost of rife :)

**Comment by Mar2ck** [comment]
I'm currently busy with university work, i'll update when i have free time again

**Comment by Tsubajashi** [comment]
i would love to try to fix it myself, and then push it as a pull request. would you mind telling me how you compiled all these .py into the .exe you provide for windows installs? i can somewhat understand how python itself works, so it would be pretty easy to fix it up for me.

**Comment by Tsubajashi** [comment]
Just saw that you added my pull request. i thank you for that. i will close that issue now since its resolved :)
